###############################################################################
###### cpolyc schematic PRIMLIB  <vs>  cpolyc layout PRIMLIB area="5.78n" c="5p" l="76.45u" perimeter="304.2u" rbottom="Cont" rleft="Cont" rright="Cont" rtop="Cont" id_=6cdfb038bdd4c61d in1=C0
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of unstable instance parameter values.
###############################################################################
   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(CPOLYA) CAP                                      1       1
                                             ------  ------
Total                                             1       1

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(CPOLYA) CAP                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                             1       1           1       1

*******************************************************************************
****** Current_Voltage_Reference schematic YAOWEN  <vs>  Current_Voltage_Reference layout YAOWEN
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(NMOS4) MOS                                      58       0*
(RPOLYH) RES                                      3       3
(cpolyc schematic PRIMLIB, cpolyc) Cell           4       2*
(PMOS4) MOS                                      68       1*
(_, nmos4 layout PRIMLIB l="10u" ...) Cell        0      40*
(_, nmos4 layout PRIMLIB l="10u" ...) Cell        0      18*
(_, pmos4 layout PRIMLIB l="10u" ...) Cell        0      17*
(_, pmos4 layout PRIMLIB l="1u" i...) Cell        0       8*
(_, pmos4 layout PRIMLIB l="30u" ...) Cell        0      28*
(_, pmos4 layout PRIMLIB l="2u" w...) Cell        0      14*
(CPOLYA) CAP                                      0       2*
                                             ------  ------
Total                                           133     133

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                      58      58          10      10
(PMOS4) MOS                                      68      68          26      26
(RPOLYH) RES                                      3       3           3       3
(CPOLYA) CAP                                      4       4           4       4
                                             ------  ------      ------  ------
Total                                           133     133          43      43

Schematic and Layout Match
