#!/bin/sh -f
#--------------------------------------------------------------------------------------
# THE RUN FILE created by Cadence Extraction Quantus UI Version 24.1.0-p089
#--------------------------------------------------------------------------------------

quantus  -log_file /home/saul/projects/IL2244_VT26_SAUL/ASSURA_LVS/opamp_ws_f/qrc.opamp_ws_f.log -cmd /home/saul/projects/IL2244_VT26_SAUL/ASSURA_LVS/opamp_ws_f/qrc.opamp_ws_f.ccl 
