0 0 dataAuditErrors
350 0 DEVICE Error: Illegal nmosh device
798 0 Process Modules : PHDNWA850 not available for this process module
802 0 Process Modules : PHDNWB850 not available for this process module
804 0 Version od SBD5 obsolte or missing
812 0 Process Modules : SBD5 not available for this process module
1288 0 ERC Warning : Name of Spiral not identified
1289 0 ERC Warning : INDDEF does not define a correct spiral or is not valid for this process
1306 0 ERC Warning : illegal layer under spiral
1319 0 ERC Warning : Each INDDEF shape must be marked with a single INDDEF text label
1321 0 ERC Warning : multiple text on INDEF
1324 0 Error: METRES overlapping CONT or VIAx
1328 0 Error: MET1RES overlapping CONT or VIA1
1332 0 Error: MET2RES overlapping VIA1 or VIA2
1336 0 Error: MET3RES overlapping VIA2 or VIA3
1339 0 Error: MET4RES overlapping VIA3
1351 0 Error: MET1 resistors (shorts) must be rectangular
1353 0 Error: Number of MET1 resistor terminals != 2
1364 0 Error: MET2 resistors (shorts) must be rectangular
1366 0 Error: Number of MET2 resistor terminals != 2
1377 0 Error: MET3 resistors (shorts) must be rectangular
1379 0 Error: Number of MET3 resistor terminals != 2
1390 0 Error: MET4 resistors (shorts) must be rectangular
1392 0 Error: Number of MET4 resistor terminals != 2
1402 0 RVIA1 Definition layer: does not open all via conncetion, is shorted
1405 0 RVIA1 Definition layer: truncates via1, device shorted
1406 0 RVIA1 Definition layer: does not define a device
1410 0 RVIA1 Definition layer: over METRES
1417 0 RVIA2 Definition layer: does not open all via conncetion, is shorted
1420 0 RVIA2 Definition layer: truncates via2, device shorted
1421 0 RVIA2 Definition layer : does not define a device
1425 0 RVIA2 Definition layer: over METRES
1433 0 RVIA3 Definition layer: does not open all via conncetion, is shorted
1436 0 RVIA3 Definition layer: truncates via3, device shorted
1437 0 RVIA3 Definition layer : does not define a device
1441 0 RVIA3 Definition layer: over METRES
1566 0 ERROR : POLY1 pin outside poly1
1567 0 ERROR : MET1 pin outside met1
1568 0 ERROR : MET2 pin outside met2
1569 0 ERROR: PADTSV pin outside METTSV
1571 0 ERROR : MET3 pin outside met3
1573 0 ERROR : MET4 pin outside met4
1574 0 ERROR : PAD pin outside pad metal
3625 0 # INFO: Don't use -resimulate_extracted- Switch for standard LVS but only for QRC! #
3627 0 # C35B4 ENG - 183 Rev9 (Last updated 26-Apr-2017 12:48) #
3928 0 malformed device NMOSH_device
3929 0 malformed device NMOSMH_device
3930 0 malformed device NMOS30M_device
3931 0 malformed device NMOS18T_device
3932 0 malformed device ESDPD12_device
3933 0 malformed device ESDPD18_device
3934 0 malformed device ESDPD26_device
3935 0 malformed device ESDPD30_device
3936 0 malformed device ESDFDN5_device
3937 0 malformed device ESDGCN5_device
3938 0 malformed device ESDFDP5_device
3939 0 malformed device ESDGCP5_device
3940 0 malformed device RNWELL_device
3941 0 malformed device RDIFFP_device
3942 0 malformed device RPOLY2_PSUB_device
3943 0 malformed device RPOLY2_NTUB_device
3944 0 malformed device RPOLY2PH_PSUB_device
3945 0 malformed device RPOLY2PH_NTUB_device
3946 0 malformed device RPOLYH_PSUB_device
3947 0 malformed device RPOLYH_NTUB_device
3948 0 malformed device RPOLY1_PSUB_device
3949 0 malformed device RPOLY1_NTUB_device
3950 0 malformed device PFUSE_device
3951 0 malformed device tsv_dev
3952 0 malformed device LAT2_device
3953 0 malformed device VERT10_device
3954 0 malformed device CPOLY_PSUB_device
3955 0 malformed device CPOLY_NTUB_device
3956 0 malformed device CVAR_device
3957 0 malformed device PROBE_device
3958 0 malformed device NMOSRF_device
3959 0 malformed device PMOSRF_device
3960 0 malformed device CPOLYRF_device
3961 0 malformed device RPOLY2RF_device
3962 0 malformed device RPOLYHRF_device
3963 0 malformed device SP014S300D_device
3964 0 malformed device SP020S180D_device
3965 0 malformed device SP026S200D_device
3966 0 malformed device SP037S180D_device
3967 0 malformed device SP047S180D_device
3968 0 malformed device SP050S155D_device
3969 0 malformed device SP090S155D_device
4507 0 unstable device for SP090S155D_device_Device_100
4508 0 unpreserved device SP090S155D_device_Device_100
4509 0 unstable device for SP050S155D_device_Device_99
4510 0 unpreserved device SP050S155D_device_Device_99
4511 0 unstable device for SP047S180D_device_Device_98
4512 0 unpreserved device SP047S180D_device_Device_98
4513 0 unstable device for SP037S180D_device_Device_97
4514 0 unpreserved device SP037S180D_device_Device_97
4515 0 unstable device for SP026S200D_device_Device_96
4516 0 unpreserved device SP026S200D_device_Device_96
4517 0 unstable device for SP020S180D_device_Device_95
4518 0 unpreserved device SP020S180D_device_Device_95
4519 0 unstable device for SP014S300D_device_Device_94
4520 0 unpreserved device SP014S300D_device_Device_94
4521 0 unstable device for RPOLYHRF_device_RES_93
4522 0 unpreserved device RPOLYHRF_device_RES_93
4523 0 unstable device for RPOLY2RF_device_RES_92
4524 0 unpreserved device RPOLY2RF_device_RES_92
4525 0 unstable device for CPOLYRF_device_CAP_91
4526 0 unpreserved device CPOLYRF_device_CAP_91
4527 0 unstable device for PMOSRF_device_Device_90
4528 0 unpreserved device PMOSRF_device_Device_90
4529 0 unstable device for NMOSRF_device_Device_89
4530 0 unpreserved device NMOSRF_device_Device_89
4531 0 unstable device for PROBE_device_Device_88
4532 0 unpreserved device PROBE_device_Device_88
4533 0 unstable device for CPMIM_device_Device_87
4534 0 unpreserved device CPMIM_device_Device_87
4535 0 unstable device for CMIM_device_no_cpmim_Device_86
4536 0 unpreserved device CMIM_device_no_cpmim_Device_86
4537 0 unstable device for CVAR_device_Device_85
4538 0 unpreserved device CVAR_device_Device_85
4539 0 unstable device for CPOLY_NTUB_device_CAP_84
4540 0 unpreserved device CPOLY_NTUB_device_CAP_84
4541 0 unstable device for CPOLY_PSUB_device_CAP_83
4542 0 unpreserved device CPOLY_PSUB_device_CAP_83
4543 0 unstable device for VERT10_device_BJT_82
4544 0 unpreserved device VERT10_device_BJT_82
4545 0 unstable device for VERT3_device_Device_81
4546 0 unpreserved device VERT3_device_Device_81
4547 0 unstable device for LAT2_device_Device_80
4548 0 unpreserved device LAT2_device_Device_80
4549 0 unstable device for tsv_dev_Device_79
4550 0 unpreserved device tsv_dev_Device_79
4551 0 unstable device for RVIA3_device_RES_78
4552 0 unpreserved device RVIA3_device_RES_78
4553 0 unstable device for RVIA2_device_RES_77
4554 0 unpreserved device RVIA2_device_RES_77
4555 0 unstable device for RVIA1_device_RES_76
4556 0 unpreserved device RVIA1_device_RES_76
4557 0 unstable device for RMET4_device_RES_75
4558 0 unpreserved device RMET4_device_RES_75
4559 0 unstable device for RMET3_device_RES_74
4560 0 unpreserved device RMET3_device_RES_74
4561 0 unstable device for RMET2_device_RES_73
4562 0 unpreserved device RMET2_device_RES_73
4563 0 unstable device for RMET1_device_RES_72
4564 0 unpreserved device RMET1_device_RES_72
4565 0 unstable device for PFUSE_device_RES_71
4566 0 unpreserved device PFUSE_device_RES_71
4567 0 unstable device for RPOLY1_NTUB_device_RES_70
4568 0 unpreserved device RPOLY1_NTUB_device_RES_70
4569 0 unstable device for RPOLY1_PSUB_device_RES_69
4570 0 unpreserved device RPOLY1_PSUB_device_RES_69
4571 0 unstable device for RPOLYZ_NTUB_device_Device_68
4572 0 unpreserved device RPOLYZ_NTUB_device_Device_68
4573 0 unstable device for RPOLYZ_PSUB_device_Device_67
4574 0 unpreserved device RPOLYZ_PSUB_device_Device_67
4575 0 unstable device for RPOLYH_NTUB_device_RES_66
4576 0 unpreserved device RPOLYH_NTUB_device_RES_66
4577 0 unstable device for RPOLYH_PSUB_device_RES_65
4578 0 unpreserved device RPOLYH_PSUB_device_RES_65
4579 0 unstable device for RPOLY2PH_NTUB_device_RES_64
4580 0 unpreserved device RPOLY2PH_NTUB_device_RES_64
4581 0 unstable device for RPOLY2PH_PSUB_device_RES_63
4582 0 unpreserved device RPOLY2PH_PSUB_device_RES_63
4583 0 unstable device for RPOLY2P_NTUB_device_Device_62
4584 0 unpreserved device RPOLY2P_NTUB_device_Device_62
4585 0 unstable device for RPOLY2P_PSUB_device_Device_61
4586 0 unpreserved device RPOLY2P_PSUB_device_Device_61
4587 0 unstable device for RPOLY2_NTUB_device_RES_60
4588 0 unpreserved device RPOLY2_NTUB_device_RES_60
4589 0 unstable device for RPOLY2_PSUB_device_RES_59
4590 0 unpreserved device RPOLY2_PSUB_device_RES_59
4591 0 unstable device for RDIFFN_device_RES_58
4592 0 unpreserved device RDIFFN_device_RES_58
4593 0 unstable device for RDIFFP_device_RES_57
4594 0 unpreserved device RDIFFP_device_RES_57
4595 0 unstable device for RNWELL_device_RES_56
4596 0 unpreserved device RNWELL_device_RES_56
4597 0 unstable device for ESDGCP5_device_Device_55
4598 0 unpreserved device ESDGCP5_device_Device_55
4599 0 unstable device for ESDFDP5_device_Device_54
4600 0 unpreserved device ESDFDP5_device_Device_54
4601 0 unstable device for ESDGCN5_device_Device_53
4602 0 unpreserved device ESDGCN5_device_Device_53
4603 0 unstable device for ESDFDN5_device_Device_52
4604 0 unpreserved device ESDFDN5_device_Device_52
4605 0 unstable device for ESDPD30_device_Device_51
4606 0 unpreserved device ESDPD30_device_Device_51
4607 0 unstable device for ESDPD26_device_Device_50
4608 0 unpreserved device ESDPD26_device_Device_50
4609 0 unstable device for ESDPD18_device_Device_49
4610 0 unpreserved device ESDPD18_device_Device_49
4611 0 unstable device for ESDPD12_device_Device_48
4612 0 unpreserved device ESDPD12_device_Device_48
4613 0 unstable device for SBD5_device_sbdcon_Device_47
4614 0 unpreserved device SBD5_device_sbdcon_Device_47
4615 0 unstable device for PHDNWB850_device_pad_barc_Device_46
4616 0 unpreserved device PHDNWB850_device_pad_barc_Device_46
4617 0 unstable device for PHDNWA850_device_ntub_Device_45
4618 0 unpreserved device PHDNWA850_device_ntub_Device_45
4619 0 unstable device for ZD2SM24_device_DIODE_44
4620 0 unpreserved device ZD2SM24_device_DIODE_44
4621 0 unstable device for P_NWD_device_DIODE_43
4622 0 unpreserved device P_NWD_device_DIODE_43
4623 0 unstable device for NWD_device_DIODE_42
4624 0 unpreserved device NWD_device_DIODE_42
4625 0 unstable device for P_PD_device_DIODE_41
4626 0 unpreserved device P_PD_device_DIODE_41
4627 0 unstable device for PD_device_DIODE_40
4628 0 unpreserved device PD_device_DIODE_40
4629 0 unstable device for P_ND_device_DIODE_39
4630 0 unpreserved device P_ND_device_DIODE_39
4631 0 unstable device for ND_device_DIODE_38
4632 0 unpreserved device ND_device_DIODE_38
4633 0 unstable device for PMOS30M_device_Device_37
4634 0 unpreserved device PMOS30M_device_Device_37
4635 0 unstable device for PMOSD30M_device_Device_36
4636 0 unpreserved device PMOSD30M_device_Device_36
4637 0 unstable device for NMOS18T_device_Device_35
4638 0 unpreserved device NMOS18T_device_Device_35
4639 0 unstable device for NMOS30M_device_Device_34
4640 0 unpreserved device NMOS30M_device_Device_34
4641 0 unstable device for NMOSMHL_device_Device_33
4642 0 unpreserved device NMOSMHL_device_Device_33
4643 0 unstable device for NMOSHL_device_Device_32
4644 0 unpreserved device NMOSHL_device_Device_32
4645 0 unstable device for NMOSMH_device_Device_31
4646 0 unpreserved device NMOSMH_device_Device_31
4647 0 unstable device for NMOSH_device_Device_30
4648 0 unpreserved device NMOSH_device_Device_30
4649 0 unstable device for PMOSMW_2N_device_Device_29
4650 0 unpreserved device PMOSMW_2N_device_Device_29
4651 0 unstable device for PMOSMW_3N_device_Device_28
4652 0 unpreserved device PMOSMW_3N_device_Device_28
4653 0 unstable device for PMOSMW_4N_device_Device_27
4654 0 unpreserved device PMOSMW_4N_device_Device_27
4655 0 unstable device for PMOSW_2N_device_Device_26
4656 0 unpreserved device PMOSW_2N_device_Device_26
4657 0 unstable device for PMOSW_3N_device_Device_25
4658 0 unpreserved device PMOSW_3N_device_Device_25
4659 0 unstable device for PMOSW_4N_device_Device_24
4660 0 unpreserved device PMOSW_4N_device_Device_24
4661 0 unstable device for NMOSMW_2N_device_Device_23
4662 0 unpreserved device NMOSMW_2N_device_Device_23
4663 0 unstable device for NMOSMW_3N_device_Device_22
4664 0 unpreserved device NMOSMW_3N_device_Device_22
4665 0 unstable device for NMOSMW_4N_device_Device_21
4666 0 unpreserved device NMOSMW_4N_device_Device_21
4667 0 unstable device for NMOSW_2N_device_Device_20
4668 0 unpreserved device NMOSW_2N_device_Device_20
4669 0 unstable device for NMOSW_3N_device_Device_19
4670 0 unpreserved device NMOSW_3N_device_Device_19
4671 0 unstable device for NMOSW_4N_device_Device_18
4672 0 unpreserved device NMOSW_4N_device_Device_18
4673 0 unstable device for PMOSML_WAFFLE_device_Device_17
4674 0 unpreserved device PMOSML_WAFFLE_device_Device_17
4675 0 unstable device for DPMOSM_device_Device_16
4676 0 unpreserved device DPMOSM_device_Device_16
4677 0 unstable device for PMOSML_device_Device_15
4678 0 unpreserved device PMOSML_device_Device_15
4679 0 unstable device for PMOSL_WAFFLE_device_Device_14
4680 0 unpreserved device PMOSL_WAFFLE_device_Device_14
4681 0 unstable device for PMOSL_device_Device_13
4682 0 unpreserved device PMOSL_device_Device_13
4683 0 unstable device for NMOSML_WAFFLE_device_Device_12
4684 0 unpreserved device NMOSML_WAFFLE_device_Device_12
4685 0 unstable device for NMOSML_device_Device_11
4686 0 unpreserved device NMOSML_device_Device_11
4687 0 unstable device for NMOSL_WAFFLE_device_Device_10
4688 0 unpreserved device NMOSL_WAFFLE_device_Device_10
4689 0 unstable device for NMOSL_device_Device_9
4690 0 unpreserved device NMOSL_device_Device_9
4691 0 unstable device for PMOSM_WAFFLE_device_Device_8
4692 0 unpreserved device PMOSM_WAFFLE_device_Device_8
4693 0 unstable device for PMOSM_device_MOS_7
4694 0 unpreserved device PMOSM_device_MOS_7
4695 0 unstable device for PMOS_WAFFLE_device_Device_6
4696 0 unpreserved device PMOS_WAFFLE_device_Device_6
4697 0 unstable device for PMOS_device_MOS_5
4698 0 unpreserved device PMOS_device_MOS_5
4699 0 unstable device for NMOSM_WAFFLE_device_Device_4
4700 0 unpreserved device NMOSM_WAFFLE_device_Device_4
4701 0 unstable device for NMOSM_device_MOS_3
4702 0 unpreserved device NMOSM_device_MOS_3
4703 0 unstable device for NMOS_WAFFLE_device_Device_2
4704 0 unpreserved device NMOS_WAFFLE_device_Device_2
4705 0 unstable device for NMOS_device_MOS_1
4706 0 unpreserved device NMOS_device_MOS_1
