*******************************************************************************
****** Constant_gm schematic YAOWEN  <vs>  Constant_gm layout YAOWEN
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOS4) MOS                                      47      47
(RPOLYH) RES                                      1       1
(NMOS4) MOS                                      12      12
                                             ------  ------
Total                                            60      60

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                      12      12           5       5
(PMOS4) MOS                                      47      47          14      14
(RPOLYH) RES                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                            60      60          20      20

Schematic and Layout Match
