set -e
set -x

rex -dp_comm_string 1,edatools,39107 -V -m -pd -I# -scale 1 -tech /opt/pdk/ams/410/assura/c35b4/c35b4c3/RCX-typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CPOLY_NTUB_device_CAP_84_net_poly2_cvia,CPOLY_NTUB_device_CAP_84_net_poly1_cvia:RPOLYH_NTUB_device_RES_66_rvia -rP res.mod -mp mprexaiCqvVJ np_rnet_met1::met1_cut - rnet_via1_net_met2_net_met1,1,x rnet_poly2con_net_met1_net_poly2__c,1,t rnet_poly2con_net_met1_net_poly2,1,T rnet_poly1con_net_met1_net_poly1,1,T rnet_pdiffcon_net_met1_net_subtap,1,t rnet_pdiffcon_net_met1_net_psd,1,t rnet_ndiffcon_net_met1_net_welltap,1,t rnet_ndiffcon_net_met1_net_nsd,1,t rnet_met1_net_met1_net_met1__c_butt_ovia,1 rnet_met1_MET1_pinshape_ovia,1 - L1T0,1,I

rex -dp_comm_string 2,edatools,39107 -V -m -pd -I# -scale 1 -tech /opt/pdk/ams/410/assura/c35b4/c35b4c3/RCX-typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CPOLY_NTUB_device_CAP_84_net_poly2_cvia,CPOLY_NTUB_device_CAP_84_net_poly1_cvia:RPOLYH_NTUB_device_RES_66_rvia -rP res.mod -mp mprexahAZy1y np_rnet_poly1::poly1_cut - CPOLY_NTUB_device_CAP_84_net_poly1_cvia,1,z PMOS_device_MOS_5_mgvia,1,z NMOS_device_MOS_1_mgvia,1,z rnet_poly1con_net_met1_net_poly1,1,x rnet_poly1con_net_met1__c_net_poly1,1,t

rex -dp_comm_string 3,edatools,39107 -V -m -pd -I# -scale 1 -tech /opt/pdk/ams/410/assura/c35b4/c35b4c3/RCX-typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CPOLY_NTUB_device_CAP_84_net_poly2_cvia,CPOLY_NTUB_device_CAP_84_net_poly1_cvia:RPOLYH_NTUB_device_RES_66_rvia -rP res.mod -mp mprexanEcpMW np_rnet_met2::met2_cut - rnet_via2_met2_net_met3_net_met2,1,x rnet_via1_net_met2_net_met1__c,1,t rnet_via1_net_met2_net_met1,1,T rnet_met2_MET2_pinshape_ovia,1 - L2T0,1,I

rex -dp_comm_string 4,edatools,39107 -V -m -pd -I# -scale 1 -tech /opt/pdk/ams/410/assura/c35b4/c35b4c3/RCX-typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CPOLY_NTUB_device_CAP_84_net_poly2_cvia,CPOLY_NTUB_device_CAP_84_net_poly1_cvia:RPOLYH_NTUB_device_RES_66_rvia -rP res.mod -mp mprexaS5a6fy np_rnet_met3::met3_cut - rnet_via2_met2_net_met3_net_met2,1,T rnet_met3_MET3_pinshape_ovia,1 - L3T0,1,I

rex -dp_comm_string 5,edatools,39107 -V -m -pd -I# -scale 1 -tech /opt/pdk/ams/410/assura/c35b4/c35b4c3/RCX-typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CPOLY_NTUB_device_CAP_84_net_poly2_cvia,CPOLY_NTUB_device_CAP_84_net_poly1_cvia:RPOLYH_NTUB_device_RES_66_rvia -rP res.mod -mp mprexaoHKycq np_rnet_presh_trm::net_presh_trm_cut - rnet_presh_trm_net_poly2_ovia,1 rnet_presh_trm_net_poly2__c_ovia,1

rex -dp_comm_string 6,edatools,39107 -V -m -pd -I# -scale 1 -tech /opt/pdk/ams/410/assura/c35b4/c35b4c3/RCX-typical -map p2elayermapfile -wee p2elayermapfile -N NET -e2 -P CPOLY_NTUB_device_CAP_84_net_poly2_cvia,CPOLY_NTUB_device_CAP_84_net_poly1_cvia:RPOLYH_NTUB_device_RES_66_rvia -rP res.mod -mp mprexaaeXDaO np_rnet_poly2::net_poly2_cut - CPOLY_NTUB_device_CAP_84_net_poly2_cvia,1,z RPOLYH_NTUB_device_RES_66_rvia,1,z rnet_presh_trm_net_poly2_ovia,1 rnet_poly2con_net_met1_net_poly2,1,x rnet_poly2con_net_met1__c_net_poly2,1,t rnet_poly2_net_poly2_net_poly2__c_butt_ovia,1

rexmerge -V -N NET -n mprexahAZy1y,mprexaoHKycq,mprexaaeXDaO,mprexaiCqvVJ,mprexanEcpMW,mprexaS5a6fy -b np_rnet_poly1::Rnp_rnet_poly1.dev2,np_rnet_presh_trm::Rnp_rnet_presh_trm.dev2,np_rnet_poly2::Rnp_rnet_poly2.dev2,np_rnet_met1::Rnp_rnet_met1.dev2,np_rnet_met2::Rnp_rnet_met2.dev2,np_rnet_met3::Rnp_rnet_met3.dev2 -l ,,,L1T0,L2T0,L3T0 np_rnet_poly1.res,np_rnet_presh_trm.res,np_rnet_poly2.res,np_rnet_met1.res,np_rnet_met2.res,np_rnet_met3.res

