*******************************************************************************
****** cmfb_opamp1_f schematic FECG  <vs>  cmfb_opamp1_f layout FECG
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(NMOS4) MOS                                      31       2*
(PMOS4) MOS                                      53       0*
(CVAR) Generic                                    1       1
(_, nmos4 layout PRIMLIB l="1u" w...) Cell        0      26*
(_, nmos4 layout PRIMLIB l="4u" w...) Cell        0       2*
(_, nmos4 layout PRIMLIB l="1u" n...) Cell        0       2*
(_, pmos4 layout PRIMLIB l="3u" i...) Cell        0       3*
(_, pmos4 layout PRIMLIB l="350n"...) Cell        0      20*
                                             ------  ------
Total                                            85      56

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                      31      34*          8       8
(PMOS4) MOS                                      53      53           7       7
(CVAR) Generic                                    1       1           1       1
                                             ------  ------      ------  ------
Total                                            85      88          16      16

Schematic and Layout Match
