###############################################################################
###### cpolyc schematic PRIMLIB  <vs>  cpolyc layout PRIMLIB area="6.94n" c="6p" l="83.75u" perimeter="333.3u" rbottom="Cont" rleft="Cont" rright="Cont" rtop="Cont" id_=f8dc73cbdd4c61d in1=C5
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of unstable instance parameter values.
###############################################################################
   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(CPOLYA) CAP                                      1       1
                                             ------  ------
Total                                             1       1

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(CPOLYA) CAP                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                             1       1           1       1

*******************************************************************************
****** BUFFER schematic YAOWEN  <vs>  BUFFER layout YAOWEN
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOS4) MOS                                     184       0*
(cpolyc schematic PRIMLIB, cpolyc) Cell           4       2*
(RPOLYH) RES                                      9       1*
(NMOS4) MOS                                       5      10*
(_, nmos4 layout PRIMLIB l="10u" ...) Cell        0       2*
(_, nmos4 layout PRIMLIB l="4u" i...) Cell        0       2*
(_, pmos4 layout PRIMLIB l="2u" i...) Cell        0      24*
(_, rpolyhc layout PRIMLIB Bends=...) Cell        0       8*
(CPOLYA) CAP                                      0       2*
                                             ------  ------
Total                                           202      51

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                       5      14*          5       5
(PMOS4) MOS                                     184     184           7       7
(RPOLYH) RES                                      9       9           3       3
(CPOLYA) CAP                                      4       4           2       2
                                             ------  ------      ------  ------
Total                                           202     211          17      17

Schematic and Layout Match
