
// Generated by Cadence Genus(TM) Synthesis Solution 23.15-s099_1
// Generated on: May 19 2026 08:55:23 UTC (May 19 2026 08:55:23 UTC)

// Verification Directory fv/il2244_dig 

module il2244_dig(reset_l, porborn, SPI_CS, SPI_Clk, SPI_MOSI,
     fECG_filter, fECG_gain, fECG_BG_sel, BIO_Gain, Bio_Ptat_EN,
     Bio_Calib_EN, ECG_filter, ECG_gain, ECG_BG_sel);
  input reset_l, porborn, SPI_CS, SPI_Clk, SPI_MOSI;
  output [2:0] fECG_filter, fECG_gain, ECG_filter;
  output fECG_BG_sel, Bio_Ptat_EN, Bio_Calib_EN, ECG_BG_sel;
  output [3:0] BIO_Gain, ECG_gain;
  wire reset_l, porborn, SPI_CS, SPI_Clk, SPI_MOSI;
  wire [2:0] fECG_filter, fECG_gain, ECG_filter;
  wire fECG_BG_sel, Bio_Ptat_EN, Bio_Calib_EN, ECG_BG_sel;
  wire [3:0] BIO_Gain, ECG_gain;
  wire [5:0] spi_Rx_count;
  wire [39:0] spi_Rx_data_temp;
  wire [31:0] conf1;
  wire [31:0] conf0;
  wire UNCONNECTED, UNCONNECTED0, UNCONNECTED1, UNCONNECTED2,
       UNCONNECTED3, UNCONNECTED4, UNCONNECTED5, UNCONNECTED6;
  wire UNCONNECTED7, UNCONNECTED8, UNCONNECTED9, UNCONNECTED10,
       UNCONNECTED11, UNCONNECTED12, UNCONNECTED13, UNCONNECTED14;
  wire UNCONNECTED15, UNCONNECTED16, UNCONNECTED17, UNCONNECTED18,
       UNCONNECTED19, UNCONNECTED20, UNCONNECTED21, UNCONNECTED22;
  wire UNCONNECTED23, UNCONNECTED24, UNCONNECTED25, UNCONNECTED26,
       UNCONNECTED27, UNCONNECTED28, UNCONNECTED29, UNCONNECTED30;
  wire UNCONNECTED31, UNCONNECTED32, UNCONNECTED33, UNCONNECTED34,
       UNCONNECTED35, UNCONNECTED36, UNCONNECTED37, UNCONNECTED38;
  wire UNCONNECTED39, UNCONNECTED40, UNCONNECTED41, UNCONNECTED42,
       UNCONNECTED43, UNCONNECTED44, UNCONNECTED45, UNCONNECTED46;
  wire UNCONNECTED47, UNCONNECTED48, UNCONNECTED49, UNCONNECTED50,
       UNCONNECTED51, UNCONNECTED52, UNCONNECTED53, UNCONNECTED54;
  wire UNCONNECTED55, UNCONNECTED56, UNCONNECTED57, n_0, n_1, n_2, n_3,
       n_4;
  wire n_5, n_6, n_7, n_8, n_9, n_10, n_11, n_12;
  wire n_13, n_14, n_15, n_16, n_17, n_18, n_19, n_20;
  wire n_28, n_34, n_40, n_46, n_52, n_58, n_64, n_70;
  wire n_76, n_82, n_88, n_94, n_100, n_106, n_112, n_118;
  wire n_124, n_130, n_136, n_142, n_148;
  DFCX4 \spi_Rx_count_reg[5] (.RN (n_17), .CP (SPI_Clk), .D (n_20), .Q
       (spi_Rx_count[5]), .QN (UNCONNECTED));
  XOR2X1 g434__2398(.A (spi_Rx_count[5]), .B (n_14), .Q (n_20));
  DFCSX4 \spi_conf1_reg[0] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[0]), .SI (conf1[0]), .SE (n_18), .Q
       (conf1[0]), .QN (UNCONNECTED0));
  DFCSX4 \spi_conf1_reg[2] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[2]), .SI (conf1[2]), .SE (n_18), .Q
       (conf1[2]), .QN (UNCONNECTED1));
  DFCX4 \spi_Rx_count_reg[4] (.RN (n_17), .CP (SPI_Clk), .D (n_15), .Q
       (spi_Rx_count[4]), .QN (UNCONNECTED2));
  DFCSX4 \spi_conf1_reg[1] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[1]), .SI (conf1[1]), .SE (n_18), .Q
       (conf1[1]), .QN (UNCONNECTED3));
  DFCSX4 \spi_conf1_reg[5] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[5]), .SI (conf1[5]), .SE (n_18), .Q
       (conf1[5]), .QN (UNCONNECTED4));
  DFCSX4 \spi_conf1_reg[4] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[4]), .SI (conf1[4]), .SE (n_18), .Q
       (conf1[4]), .QN (UNCONNECTED5));
  DFCSX4 \spi_conf1_reg[3] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[3]), .SI (conf1[3]), .SE (n_18), .Q
       (conf1[3]), .QN (UNCONNECTED6));
  DFCSX4 \spi_conf1_reg[6] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[6]), .SI (conf1[6]), .SE (n_18), .Q
       (conf1[6]), .QN (UNCONNECTED7));
  DFCSX4 \spi_conf1_reg[7] (.RN (n_19), .CP (SPI_CS), .D
       (spi_Rx_data_temp[7]), .SI (conf1[7]), .SE (n_18), .Q
       (conf1[7]), .QN (UNCONNECTED8));
  DFCSX4 \spi_conf0_reg[10] (.RN (n_19), .CP (SPI_CS), .D (conf0[10]),
       .SI (spi_Rx_data_temp[10]), .SE (n_16), .Q (conf0[10]), .QN
       (UNCONNECTED9));
  DFCSX4 \spi_conf0_reg[6] (.RN (n_19), .CP (SPI_CS), .D (conf0[6]),
       .SI (spi_Rx_data_temp[6]), .SE (n_16), .Q (conf0[6]), .QN
       (UNCONNECTED10));
  DFCSX4 \spi_conf0_reg[7] (.RN (n_19), .CP (SPI_CS), .D (conf0[7]),
       .SI (spi_Rx_data_temp[7]), .SE (n_16), .Q (conf0[7]), .QN
       (UNCONNECTED11));
  DFCSX4 \spi_conf0_reg[8] (.RN (n_19), .CP (SPI_CS), .D (conf0[8]),
       .SI (spi_Rx_data_temp[8]), .SE (n_16), .Q (conf0[8]), .QN
       (UNCONNECTED12));
  DFCSX4 \spi_conf0_reg[9] (.RN (n_19), .CP (SPI_CS), .D (conf0[9]),
       .SI (spi_Rx_data_temp[9]), .SE (n_16), .Q (conf0[9]), .QN
       (UNCONNECTED13));
  DFCSX4 \spi_conf0_reg[2] (.RN (n_19), .CP (SPI_CS), .D (conf0[2]),
       .SI (spi_Rx_data_temp[2]), .SE (n_16), .Q (conf0[2]), .QN
       (UNCONNECTED14));
  DFCSX4 \spi_conf0_reg[3] (.RN (n_19), .CP (SPI_CS), .D (conf0[3]),
       .SI (spi_Rx_data_temp[3]), .SE (n_16), .Q (conf0[3]), .QN
       (UNCONNECTED15));
  DFCSX4 \spi_conf0_reg[12] (.RN (n_19), .CP (SPI_CS), .D (conf0[12]),
       .SI (spi_Rx_data_temp[12]), .SE (n_16), .Q (conf0[12]), .QN
       (UNCONNECTED16));
  DFCSX4 \spi_conf0_reg[0] (.RN (n_19), .CP (SPI_CS), .D (conf0[0]),
       .SI (spi_Rx_data_temp[0]), .SE (n_16), .Q (conf0[0]), .QN
       (UNCONNECTED17));
  DFCSX4 \spi_conf0_reg[1] (.RN (n_19), .CP (SPI_CS), .D (conf0[1]),
       .SI (spi_Rx_data_temp[1]), .SE (n_16), .Q (conf0[1]), .QN
       (UNCONNECTED18));
  DFCSX4 \spi_conf0_reg[4] (.RN (n_19), .CP (SPI_CS), .D (conf0[4]),
       .SI (spi_Rx_data_temp[4]), .SE (n_16), .Q (conf0[4]), .QN
       (UNCONNECTED19));
  DFCSX4 \spi_conf0_reg[5] (.RN (n_19), .CP (SPI_CS), .D (conf0[5]),
       .SI (spi_Rx_data_temp[5]), .SE (n_16), .Q (conf0[5]), .QN
       (UNCONNECTED20));
  DFCSX4 \spi_conf0_reg[11] (.RN (n_19), .CP (SPI_CS), .D (conf0[11]),
       .SI (spi_Rx_data_temp[11]), .SE (n_16), .Q (conf0[11]), .QN
       (UNCONNECTED21));
  HAX3 g436__5107(.A (spi_Rx_count[4]), .B (n_12), .CO (n_14), .SUM
       (n_15));
  NAND2X2 g461__6260(.A (n_11), .B (spi_Rx_data_temp[32]), .Q (n_18));
  DFCX4 \spi_Rx_count_reg[3] (.RN (n_17), .CP (SPI_Clk), .D (n_13), .Q
       (spi_Rx_count[3]), .QN (n_1));
  NOR2X3 g462__4319(.A (n_10), .B (spi_Rx_data_temp[32]), .Q (n_16));
  HAX3 g459__8428(.A (spi_Rx_count[3]), .B (n_8), .CO (n_12), .SUM
       (n_13));
  CLKINVX1 g464(.A (n_10), .Q (n_11));
  NAND3X1 g465__5526(.A (spi_Rx_count[5]), .B (n_7), .C (n_0), .Q
       (n_10));
  DFCX4 \spi_Rx_count_reg[2] (.RN (n_17), .CP (SPI_Clk), .D (n_9), .Q
       (spi_Rx_count[2]), .QN (UNCONNECTED22));
  HAX3 g463__6783(.A (spi_Rx_count[2]), .B (n_5), .CO (n_8), .SUM
       (n_9));
  NOR4X1 g484__3680(.A (n_1), .B (n_4), .C (spi_Rx_count[4]), .D
       (spi_Rx_count[2]), .Q (n_7));
  DFCX4 \spi_Rx_count_reg[1] (.RN (n_17), .CP (SPI_Clk), .D (n_6), .Q
       (spi_Rx_count[1]), .QN (UNCONNECTED23));
  NOR2X3 g502__1617(.A (n_5), .B (n_3), .Q (n_6));
  DFCSX4 \spi_Rx_data_temp_reg[16] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[15]), .SI (spi_Rx_data_temp[16]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[16]), .QN (UNCONNECTED24));
  DFCSX4 \spi_Rx_data_temp_reg[25] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[24]), .SI (spi_Rx_data_temp[25]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[25]), .QN (UNCONNECTED25));
  DFCSX4 \spi_Rx_data_temp_reg[28] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[27]), .SI (spi_Rx_data_temp[28]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[28]), .QN (UNCONNECTED26));
  DFCSX4 \spi_Rx_data_temp_reg[24] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[23]), .SI (spi_Rx_data_temp[24]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[24]), .QN (UNCONNECTED27));
  DFCSX4 \spi_Rx_data_temp_reg[23] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[22]), .SI (spi_Rx_data_temp[23]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[23]), .QN (UNCONNECTED28));
  DFCSX4 \spi_Rx_data_temp_reg[22] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[21]), .SI (spi_Rx_data_temp[22]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[22]), .QN (UNCONNECTED29));
  DFCSX4 \spi_Rx_data_temp_reg[20] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[19]), .SI (spi_Rx_data_temp[20]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[20]), .QN (UNCONNECTED30));
  DFCSX4 \spi_Rx_data_temp_reg[14] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[13]), .SI (spi_Rx_data_temp[14]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[14]), .QN (UNCONNECTED31));
  DFCSX4 \spi_Rx_data_temp_reg[17] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[16]), .SI (spi_Rx_data_temp[17]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[17]), .QN (UNCONNECTED32));
  DFCSX4 \spi_Rx_data_temp_reg[19] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[18]), .SI (spi_Rx_data_temp[19]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[19]), .QN (UNCONNECTED33));
  DFCSX4 \spi_Rx_data_temp_reg[18] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[17]), .SI (spi_Rx_data_temp[18]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[18]), .QN (UNCONNECTED34));
  DFCSX4 \spi_Rx_data_temp_reg[15] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[14]), .SI (spi_Rx_data_temp[15]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[15]), .QN (UNCONNECTED35));
  DFCSX4 \spi_Rx_data_temp_reg[21] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[20]), .SI (spi_Rx_data_temp[21]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[21]), .QN (UNCONNECTED36));
  DFCSX4 \spi_Rx_data_temp_reg[12] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[11]), .SI (spi_Rx_data_temp[12]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[12]), .QN (UNCONNECTED37));
  DFCSX4 \spi_Rx_data_temp_reg[10] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[9]), .SI (spi_Rx_data_temp[10]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[10]), .QN (UNCONNECTED38));
  DFCSX4 \spi_Rx_data_temp_reg[6] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[5]), .SI (spi_Rx_data_temp[6]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[6]), .QN (UNCONNECTED39));
  DFCSX4 \spi_Rx_data_temp_reg[5] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[4]), .SI (spi_Rx_data_temp[5]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[5]), .QN (UNCONNECTED40));
  CLKINVX1 g503(.A (n_3), .Q (n_4));
  DFCSX4 \spi_Rx_data_temp_reg[33] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[32]), .SI (spi_Rx_data_temp[33]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[33]), .QN (UNCONNECTED41));
  DFCSX4 \spi_Rx_data_temp_reg[13] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[12]), .SI (spi_Rx_data_temp[13]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[13]), .QN (UNCONNECTED42));
  DFCSX4 \spi_Rx_data_temp_reg[30] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[29]), .SI (spi_Rx_data_temp[30]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[30]), .QN (UNCONNECTED43));
  DFCSX4 \spi_Rx_data_temp_reg[27] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[26]), .SI (spi_Rx_data_temp[27]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[27]), .QN (UNCONNECTED44));
  DFCSX4 \spi_Rx_data_temp_reg[29] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[28]), .SI (spi_Rx_data_temp[29]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[29]), .QN (UNCONNECTED45));
  DFCSX4 \spi_Rx_data_temp_reg[31] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[30]), .SI (spi_Rx_data_temp[31]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[31]), .QN (UNCONNECTED46));
  DFCSX4 \spi_Rx_data_temp_reg[26] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[25]), .SI (spi_Rx_data_temp[26]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[26]), .QN (UNCONNECTED47));
  DFCSX4 \spi_Rx_data_temp_reg[11] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[10]), .SI (spi_Rx_data_temp[11]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[11]), .QN (UNCONNECTED48));
  DFCSX4 \spi_Rx_data_temp_reg[8] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[7]), .SI (spi_Rx_data_temp[8]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[8]), .QN (UNCONNECTED49));
  DFCSX4 \spi_Rx_data_temp_reg[9] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[8]), .SI (spi_Rx_data_temp[9]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[9]), .QN (UNCONNECTED50));
  DFCSX4 \spi_Rx_data_temp_reg[3] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[2]), .SI (spi_Rx_data_temp[3]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[3]), .QN (UNCONNECTED51));
  DFCSX4 \spi_Rx_data_temp_reg[2] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[1]), .SI (spi_Rx_data_temp[2]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[2]), .QN (UNCONNECTED52));
  DFCSX4 \spi_Rx_data_temp_reg[0] (.RN (n_19), .CP (SPI_Clk), .D
       (SPI_MOSI), .SI (spi_Rx_data_temp[0]), .SE (SPI_CS), .Q
       (spi_Rx_data_temp[0]), .QN (UNCONNECTED53));
  DFCSX4 \spi_Rx_data_temp_reg[32] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[31]), .SI (spi_Rx_data_temp[32]), .SE
       (SPI_CS), .Q (spi_Rx_data_temp[32]), .QN (UNCONNECTED54));
  DFCSX4 \spi_Rx_data_temp_reg[7] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[6]), .SI (spi_Rx_data_temp[7]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[7]), .QN (UNCONNECTED55));
  DFCSX4 \spi_Rx_data_temp_reg[4] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[3]), .SI (spi_Rx_data_temp[4]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[4]), .QN (UNCONNECTED56));
  DFCSX4 \spi_Rx_data_temp_reg[1] (.RN (n_19), .CP (SPI_Clk), .D
       (spi_Rx_data_temp[0]), .SI (spi_Rx_data_temp[1]), .SE (SPI_CS),
       .Q (spi_Rx_data_temp[1]), .QN (UNCONNECTED57));
  DFCX3 \spi_Rx_count_reg[0] (.RN (n_17), .CP (SPI_Clk), .D
       (spi_Rx_count[0]), .Q (n_2), .QN (spi_Rx_count[0]));
  NOR2X3 g504__2802(.A (spi_Rx_count[1]), .B (n_2), .Q (n_3));
  AND2X4 g506__1705(.A (n_2), .B (spi_Rx_count[1]), .Q (n_5));
  AND2X2 g507__5122(.A (porborn), .B (reset_l), .Q (n_19));
  CLKINVX1 g508(.A (spi_Rx_data_temp[33]), .Q (n_0));
  CLKINVX1 g511(.A (SPI_CS), .Q (n_17));
  CLKINVX12 drc_bufs573(.A (n_28), .Q (fECG_filter[0]));
  CLKINVX4 drc_bufs574(.A (conf0[0]), .Q (n_28));
  CLKINVX12 drc_bufs579(.A (n_34), .Q (fECG_filter[1]));
  CLKINVX4 drc_bufs580(.A (conf0[1]), .Q (n_34));
  CLKINVX12 drc_bufs585(.A (n_40), .Q (fECG_gain[0]));
  CLKINVX4 drc_bufs586(.A (conf0[3]), .Q (n_40));
  CLKINVX12 drc_bufs591(.A (n_46), .Q (BIO_Gain[0]));
  CLKINVX4 drc_bufs592(.A (conf0[7]), .Q (n_46));
  CLKINVX12 drc_bufs597(.A (n_52), .Q (BIO_Gain[1]));
  CLKINVX4 drc_bufs598(.A (conf0[8]), .Q (n_52));
  CLKINVX12 drc_bufs603(.A (n_58), .Q (fECG_gain[1]));
  CLKINVX4 drc_bufs604(.A (conf0[4]), .Q (n_58));
  CLKINVX12 drc_bufs609(.A (n_64), .Q (BIO_Gain[2]));
  CLKINVX4 drc_bufs610(.A (conf0[9]), .Q (n_64));
  CLKINVX12 drc_bufs615(.A (n_70), .Q (BIO_Gain[3]));
  CLKINVX4 drc_bufs616(.A (conf0[10]), .Q (n_70));
  CLKINVX12 drc_bufs621(.A (n_76), .Q (fECG_filter[2]));
  CLKINVX4 drc_bufs622(.A (conf0[2]), .Q (n_76));
  CLKINVX12 drc_bufs627(.A (n_82), .Q (Bio_Calib_EN));
  CLKINVX4 drc_bufs628(.A (conf0[12]), .Q (n_82));
  CLKINVX12 drc_bufs633(.A (n_88), .Q (fECG_gain[2]));
  CLKINVX4 drc_bufs634(.A (conf0[5]), .Q (n_88));
  CLKINVX12 drc_bufs639(.A (n_94), .Q (Bio_Ptat_EN));
  CLKINVX4 drc_bufs640(.A (conf0[11]), .Q (n_94));
  CLKINVX12 drc_bufs645(.A (n_100), .Q (fECG_BG_sel));
  CLKINVX4 drc_bufs646(.A (conf0[6]), .Q (n_100));
  CLKINVX12 drc_bufs651(.A (n_106), .Q (ECG_gain[3]));
  CLKINVX4 drc_bufs652(.A (conf1[6]), .Q (n_106));
  CLKINVX12 drc_bufs657(.A (n_112), .Q (ECG_BG_sel));
  CLKINVX4 drc_bufs658(.A (conf1[7]), .Q (n_112));
  CLKINVX12 drc_bufs663(.A (n_118), .Q (ECG_gain[0]));
  CLKINVX4 drc_bufs664(.A (conf1[3]), .Q (n_118));
  CLKINVX12 drc_bufs669(.A (n_124), .Q (ECG_filter[0]));
  CLKINVX4 drc_bufs670(.A (conf1[0]), .Q (n_124));
  CLKINVX12 drc_bufs675(.A (n_130), .Q (ECG_filter[2]));
  CLKINVX4 drc_bufs676(.A (conf1[2]), .Q (n_130));
  CLKINVX12 drc_bufs681(.A (n_136), .Q (ECG_gain[2]));
  CLKINVX4 drc_bufs682(.A (conf1[5]), .Q (n_136));
  CLKINVX12 drc_bufs687(.A (n_142), .Q (ECG_gain[1]));
  CLKINVX4 drc_bufs688(.A (conf1[4]), .Q (n_142));
  CLKINVX12 drc_bufs693(.A (n_148), .Q (ECG_filter[1]));
  CLKINVX4 drc_bufs694(.A (conf1[1]), .Q (n_148));
endmodule

