###############################################################################
###### cpolyc schematic PRIMLIB  <vs>  cpolyc layout PRIMLIB area="5.78n" c="5p" l="76.45u" perimeter="304.2u" rbottom="Cont" rleft="Cont" rright="Cont" rtop="Cont" id_=6cdfb038bdd4c61d in1=C0
###############################################################################
###### This report is for informational purposes only. This cell
###### has been expanded because of unstable instance parameter values.
###############################################################################
   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(CPOLYA) CAP                                      1       1
                                             ------  ------
Total                                             1       1

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(CPOLYA) CAP                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                             1       1           1       1

*******************************************************************************
****** V500_20 schematic POWER_TRACKS  <vs>  V500_20 layout POWER_TRACKS
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(cpolyc schematic PRIMLIB, cpolyc) Cell           1       0*
(CPOLYA) CAP                                      0       1*
                                             ------  ------
Total                                             1       1

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(CPOLYA) CAP                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                             1       1           1       1

*******************************************************************************
****** Current_Voltage_Reference schematic YAOWEN  <vs>  Current_Voltage_Reference layout YAOWEN
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(NMOS4) MOS                                      58       0*
(RPOLYH) RES                                      3       3
(CVAR) Generic                                    4       0*
(cpolyc schematic PRIMLIB, cpolyc) Cell           2       2
(PMOS4) MOS                                      68       0*
(_, cvar layout PRIMLIB col=12 ro...) Cell        0       4*
(_, nmos4 layout PRIMLIB l="10u" ...) Cell        0      18*
(_, nmos4 layout PRIMLIB l="10u" ...) Cell        0      40*
(_, pmos4 layout PRIMLIB l="10u" ...) Cell        0      17*
(_, pmos4 layout PRIMLIB l="2u" w...) Cell        0      14*
(_, pmos4 layout PRIMLIB l="30u" ...) Cell        0      28*
(_, pmos4 layout PRIMLIB l="1u" i...) Cell        0       8*
(_, pmos4 layout PRIMLIB l="1u" w...) Cell        0       1*
                                             ------  ------
Total                                           135     135

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                      58      58          10      10
(PMOS4) MOS                                      68      68          26      26
(RPOLYH) RES                                      3       3           3       3
(CPOLYA) CAP                                      2       2           2       2
(CVAR) Generic                                    4       4           4       4
                                             ------  ------      ------  ------
Total                                           135     135          45      45

*******************************************************************************
****** V200_20 schematic POWER_TRACKS  <vs>  V200_20 layout POWER_TRACKS
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(cpolyc schematic PRIMLIB, cpolyc) Cell           1       0*
(CPOLYA) CAP                                      0       1*
                                             ------  ------
Total                                             1       1

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(CPOLYA) CAP                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                             1       1           1       1

*******************************************************************************
****** ECG_bandgap_f_v1 schematic YAOWEN  <vs>  ECG_bandgap_f_v1 layout YAOWEN
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(RPOLYH) RES                                      4       2*
(PNPVERT10) BJT                                  49       0*
(cpolyc schematic PRIMLIB, cpolyc) Cell           1       0*
(PMOS4) MOS                                     178       0*
(NMOS4) MOS                                      32       2*
(_, nmos4 layout PRIMLIB l="500n"...) Cell        0       8*
(_, nmos4 layout PRIMLIB l="10u" ...) Cell        0      11*
(_, nmos4 layout PRIMLIB l="5u" i...) Cell        0       3*
(_, nmos4 layout PRIMLIB l="40u" ...) Cell        0       8*
(_, pmos4 layout PRIMLIB l="500n"...) Cell        0       8*
(_, pmos4 layout PRIMLIB l="4u" w...) Cell        0      12*
(_, pmos4 layout PRIMLIB l="10u" ...) Cell        0       2*
(_, rpolyhc layout PRIMLIB Bends=...) Cell        0       2*
(_, vert10_4 layout PRIMLIB) Cell                 0       7*
(CPOLYA) CAP                                      0       1*
                                             ------  ------
Total                                           264      66

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                      32      32          16      16
(PMOS4) MOS                                     178     178          13      13
(RPOLYH) RES                                      4       4           4       4
(PNPVERT10) BJT                                  49      49           3       3
(CPOLYA) CAP                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                           264     264          37      37

*******************************************************************************
****** Constant_gm schematic YAOWEN  <vs>  Constant_gm layout YAOWEN
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(PMOS4) MOS                                      47      47
(RPOLYH) RES                                      1       1
(NMOS4) MOS                                      12      12
                                             ------  ------
Total                                            60      60

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(NMOS4) MOS                                      12      12           5       5
(PMOS4) MOS                                      47      47          14      14
(RPOLYH) RES                                      1       1           1       1
                                             ------  ------      ------  ------
Total                                            60      60          20      20

*******************************************************************************
****** ECG_BIAS schematic YAOWEN  <vs>  ECG_BIAS layout YAOWEN
*******************************************************************************

Filter/Reduce statistics only. Network matching was OK.
                                                                                                                                                                   
Pre-expand Statistics                      
======================                          Original       
Cell/Device                               schematic  layout
(V500_20 schematic POWER_TRACKS, V500_20) Cell            9       9
(Current_Voltage_Reference schematic YAOWEN, Current_Voltage_Reference) Cell            1       1
(V200_20 schematic POWER_TRACKS, V200_20) Cell            9       9
(ECG_bandgap_f_v1 schematic YAOWEN, ECG_bandgap_f_v1) Cell          1       1
(Constant_gm schematic YAOWEN, Constant_gm) Cell          1       1
                                             ------  ------
Total                                            21      21

Reduce Statistics
=================                               Original             Reduced
Cell/Device                               schematic  layout   schematic  layout
(Constant_gm) Cell                                1       1           1       1
(Current_Voltage_Reference) Cell                  1       1           1       1
(ECG_bandgap_f_v1) Cell                           1       1           1       1
(V200_20) Cell                                    9       9           9       9
(V500_20) Cell                                    9       9           9       9
                                             ------  ------      ------  ------
Total                                            21      21          21      21

Schematic and Layout Match
